[package]
name = "axdevice_base"
edition = "2024"
version = "0.1.0"
description = "Basic traits and structures for emulated devices in ArceOS hypervisor."
authors = ["Hui Xiao <1127751018@qq.com>"]
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0" # MulanPubL2 is not included in SPDX
categories = ["virtualization", "no-std"]
homepage = "https://github.com/arceos-hypervisor/axvisor" 

[dependencies]
cfg-if = "1.0"
serde = { version = "1.0.204", default-features = false, features = ["derive", "alloc"] }
# System independent crates provided by ArceOS.
axerrno = "0.1.0"
axaddrspace = "0.1.0"
axvmconfig = { version = "0.1.0", default-features = false }
memory_addr = "0.4"
